### ISSUE TITLE
Boto3 Error

### ISSUE THREAD

**Issue by sunnysyed** [rsummers618/HTPC_Alexa_Skill#1]
Running into an issue trying to get this to run I have entered my key from my alexa app but everytime I restart Kodi I get a error at the button and pulled this from the log. Seems to be an issue with Boto3.

`21:11:22 T:140735109705728   DEBUG: ADDON: cpluff: 'Plug-in script.service.alexa has been installed.'
21:11:23 T:123145310507008   DEBUG: CPythonInvoker(1, /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py): start processing
21:11:23 T:123145310507008   DEBUG: CPythonInvoker(1, /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py): the source file to load is "/Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py"
21:11:23 T:123145310507008   DEBUG: CPythonInvoker(1, /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py): setting the Python path to /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
21:11:23 T:123145310507008   DEBUG: CPythonInvoker(1, /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py): entering source directory /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa
21:11:23 T:123145310507008   DEBUG: CPythonInvoker(1, /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py): instantiating addon using automatically obtained id of "script.service.alexa" dependent on version 2.1.0 of the xbmc.python api
21:11:23 T:123145310507008  NOTICE: /Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py/../lib/
                                              File "/Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/service.py", line 8, in <module>
                                              File "/Users/sunny/Library/Application Support/Kodi/addons/script.service.alexa/lib/boto3/__init__.py", line 16, in <module>
`

**Comment by rsummers618** [comment]
Boto3 issues confirmed to be occuring on android/firetv/and OSX devices.

Working on a fix. 

Currently Windows and Linux are working.

**Comment by rsummers618** [comment]
Closed.

Boto3 works on OSX android etc.
