### ISSUE TITLE
navLocation error

### ISSUE THREAD

**Issue by Saiks** [rsummers618/HTPC_Alexa_Skill#2]
when copying and pasting IntentSchema.json, saving shows an error about navLocation.

Error: There was a problem with your request: Unknown slot type 'NavLocation' for slot 'NavLocation'

**Comment by mwguttman** [comment]
Having the same problem.

**Comment by rsummers618** [comment]
Did you add the navLocations slot from speech assets?

https://github.com/rsummers618/HTPC_Alexa_Skill/tree/master/Alexa/speechAssets/slots

Its a new feature, and just added.  Make sure you add it.

**Comment by Saiks** [comment]
Thanks that did the trick

**Comment by Saiks** [comment]
Question, Pulsar is no longer being developed or supported and there is a new fork 'Quasar'. Is there a  way to use that instead of Pulsar? Thanks again. Sorry for going off topic here

**Comment by rsummers618** [comment]
This will be included in the next drop.

If you need the change right away, you should just be able to replace "pulsar" with "quasar" at every instance in service.py

Issue Closed
