### ISSUE TITLE
Request: feature toggling (add settings)

### ISSUE THREAD

**Issue by bcliang** [rsummers618/HTPC_Alexa_Skill#4]
Story #4.1: As a user, I want to be able to toggle the streaming feature(s) for netflix / pulsar / quasar via the kodi UI so that I can control the source of my watched content. 

Proposed Actions:
- Update **./resources/settings.xml** with new boolean ids to enable toggling for use of netflix and/or video addon
- Update **./resources/languages/English/**\* with new strings.po. Add strings for new toggles.
- Modify service.py to use newly created settings within the script code
- Modify watch_movie and watch_episode functions to limit code execution if streaming features have been disabled.
- Add logging around failure to find requested media

Story #4.2:
As a user, I want to be able to define/customize the remote locations that the script will be contacting so that I can control where my requests are processed.

Proposed Actions:
- Update **./resources/settings.xml** with new text ids to enable definition of socket_url and socket_port
- Add documentation for making modifications within **./Alexa/src/** for custom websocket server

Will create branch and eventual pull request on bcliang/HTPC_Alexa_Skill/moresettings

**Comment by rsummers618** [comment]
re #4.1

Ideally, Nothing will be run by default. And the service will only launch addons that the user has already installed. (which can be disabled)  I haven't played enough with settings.xml to dynamically be able to show which addons the are both installed and supported in order to disable them.  If you can implement this that would be fantastic!

**Comment by bcliang** [comment]
Ran into trouble with the jsonrpc request / message return for Addons::GetAddons, so the branch is currently broken (doesn't id any video addons). https://github.com/bcliang/HTPC_Alexa_Skill/tree/moresettings

Settings changes:
![image](https://cloud.githubusercontent.com/assets/569205/13345584/c6ee6422-dc14-11e5-87ea-c309d2a28f58.png)
![image](https://cloud.githubusercontent.com/assets/569205/13345606/f478270c-dc14-11e5-9946-75935af809f8.png)
- Settings are enabled/disabled depending on the hard-coded plugin id being installed. I'm not sure how to dynamically update the toggles within the settings page. 
- Didn't add a toggle for sports streaming.

**Comment by bcliang** [comment]
Think everything's ready to go. Created a pull request https://github.com/rsummers618/HTPC_Alexa_Skill/pull/6

**Comment by bcliang** [comment]
Issue closed. The python script implements toggling of streaming sources and location information for the websocket server, and is easily extendable to other future plugins that may be supported.

Push documentation for Alexa skill socket_host / socket_port variables to release notes?
