### ISSUE TITLE
Alexa --> Kodi - can't communicate with the TV

### ISSUE THREAD

**Issue by Saiks** [rsummers618/HTPC_Alexa_Skill#5]
Don't know if anyone is having this issue. Last night she was good but now there's a problem.

Also I see that Quasar is being integrated, last night it kept referring to Pulsar even though i don't have it  install.

Thanks

**Comment by rsummers618** [comment]
The method of communication to kodi was changed last night. Queues have been replaced by a websocket.

Please make sure you are using Kodi addon v0.1.0

**Comment by Saiks** [comment]
Sorry I see the change but I don't know if i'm doing this wrong... I
installed *script.service.alexa-0.1.0.zip *and still getting the same
result. Reinstalled repository.rsummers618-1.0.zip which I believe such
point to the new version but a no go either.

**Comment by rsummers618** [comment]
Could you try again? It looks like the websocket server went down momentarily

**Comment by Saiks** [comment]
Thanks now it's working and Quasar is as well. If there is anything I can
do please don't hesitate
